[package]
name = "unified-zkvm-macros"
description = "Procedural macros for unified-zkvm guest entrypoints."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0.6", features = ["full"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
